spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&autoReconnect=true&autoReconnectForPools=true
    username: root
    password: 123456

## RabbitMQ configuration

multiplication:
  exchange: multiplication_exchange
  solved:
    key: multiplication.solved